apiVersion: v1
kind: ConfigMap
metadata:
  name: db-users-config
data:
  APP_NAME: letmeknow_database
  MONGODB_USERNAME: astolfifrancesco00
  MONGODB_PASSWORD: H6oItdTRDs1PHnDU
  MONGODB_CLUSTER: cluster0.x3jcbgn.mongodb.net
  MONGODB_DB: user
