# ConfigMap API Gateway
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  labels:
    app: api-gateway-service
data:
  APP_NAME: letmeknow_gateway
  LOGIN_ADDRESS: "http://login-service:8001"
  HOMEPAGE_ADDRESS: "http://homepage-service:8003"

---
# Deployment API Gateway
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway-service
  template:
    metadata:
      labels:
        app: api-gateway-service
    spec:
      containers:
        - name: api-gateway
          image: francescoastolfidev00/api-gateway-service:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8002
          env:
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: api-gateway-config
                  key: APP_NAME
            - name: LOGIN_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: api-gateway-config
                  key: LOGIN_ADDRESS
            - name: HOMEPAGE_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: api-gateway-config
                  key: HOMEPAGE_ADDRESS
          livenessProbe:
            httpGet:
              path: /APIgateway/health
              port: 8002
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 2
            failureThreshold: 3

---
# Service API Gateway
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
spec:
  selector:
    app: api-gateway-service
  ports:
    - port: 8002
      targetPort: 8002
  type: LoadBalancer
