apiVersion: v1
kind: Namespace
metadata:
  name: letmeknow
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: react-frontend-config
  namespace: letmeknow
data:
  REACT_APP_API_BASE_URL: "http://api-gateway-service:8002"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend
  namespace: letmeknow
  labels:
    app: react-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-frontend
  template:
    metadata:
      labels:
        app: react-frontend
    spec:
      containers:
        - name: react-frontend
          image: francescoastolfidev00/frontend-service:2.0
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: react-frontend-config
---
apiVersion: v1
kind: Service
metadata:
  name: react-frontend-lb
  namespace: letmeknow
spec:
  type: LoadBalancer
  selector:
    app: react-frontend
  ports:
    - protocol: TCP
      port: 80       # out door
      targetPort: 80 # inner door
